#!/bin/bash

cd ~/Documents/Postdoc/HIV_transmission/Code/CRP/package
cd phyloCRP/

awk '{gsub(/useDynLib(phyloCRP)/,"#useDynLib(phyloCRP)")}' NAMESPACE
perl -i -pe 's/useDynLib/#useDynLib/' NAMESPACE

cd ..
tar -cvf phyloCRP_0.1.0.tar.gz phyloCRP/

